import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,analyze,review,changeStatus,metrics,filterTickets,recommend,syncMap} from '../engine.js';
import {engineers,workStatuses} from '../data.js';
function fixture(){const state=initialState(),ticket=state.tickets[0],a=analyze(ticket);return {state,ticket,draft:{summary:a.summary,priority:a.priority,queue:a.queue,owner:recommend(state,ticket,a.queue)[0].id,note:''}};}
test('unapproved requests never create engineering work',()=>{const {state,ticket}=fixture();assert.equal(state.tickets.length,16);assert.equal(state.work.some(w=>w.source===ticket.id),false);assert.equal(metrics(state).reviewed,0);});
test('approval preserves original request and captures human corrections once',()=>{const {state,ticket,draft}=fixture(),original=ticket.description;draft.priority='Low';draft.queue='Mobile';draft.owner='maya';draft.summary='Reviewed sample summary';review(state,ticket.id,draft,'approve');const w=state.work.find(w=>w.source===ticket.id);assert.equal(w.owner,'maya');assert.equal(w.priority,'Low');assert.equal(w.summary,draft.summary);assert.equal(ticket.status,'Assigned');assert.equal(ticket.description,original);const m=metrics(state);assert.equal(m.reviewed,1);assert.equal(m.accepted,0);assert.equal(m.priorityChanged,1);assert.equal(m.routingChanged,1);assert.equal(m.summaryEdited,1);assert.throws(()=>review(state,ticket.id,draft,'approve'),/already/);assert.equal(state.work.filter(w=>w.source===ticket.id).length,1);});
test('unchanged approval is measured, merely reading suggestions is not',()=>{const {state,ticket,draft}=fixture();analyze(ticket);assert.equal(metrics(state).reviewed,0);review(state,ticket.id,draft,'approve');assert.equal(metrics(state).accepted,1);});
test('returned requests require information notes and create no work; re-review replaces feedback',()=>{const {state,ticket,draft}=fixture();assert.throws(()=>review(state,ticket.id,draft,'return'),/information/);assert.equal(metrics(state).reviewed,0);draft.note='Provide a fictional reproduction sequence.';review(state,ticket.id,draft,'return');assert.equal(ticket.status,'Awaiting Information');assert.equal(state.work.length,7);assert.equal(metrics(state).returned,1);review(state,ticket.id,draft,'approve');assert.equal(metrics(state).reviewed,1);assert.equal(metrics(state).returned,0);assert.equal(metrics(state).accepted,1);});
test('each status synchronizes source, resolution counts exclude reopened work',()=>{const {state,ticket,draft}=fixture();review(state,ticket.id,draft,'approve');const w=state.work.find(w=>w.source===ticket.id),before=metrics(state).resolved;for(const status of workStatuses){changeStatus(state,w.id,status);assert.equal(ticket.status,syncMap[status]);}assert.equal(metrics(state).resolved,before+1);changeStatus(state,w.id,'In Progress');assert.equal(metrics(state).resolved,before);assert.equal(w.resolvedAt,null);assert.ok(state.audit[0].message.includes('Status Sync Simulation'));});
test('search and all filters combine, including updated priority and status',()=>{const {state,ticket,draft}=fixture();draft.priority='Low';review(state,ticket.id,draft,'approve');assert.equal(filterTickets(state,{search:'CHECKOUT',platform:'Android',priority:'Low',status:'Assigned',category:'Payments'}).length,1);assert.equal(filterTickets(state,{search:'SUP-101',platform:'iOS'}).length,0);assert.equal(filterTickets(state,{search:'does not exist'}).length,0);});
test('recommendations are deterministic, explainable and respond to workload',()=>{const {state,ticket}=fixture();const a=recommend(state,ticket,'Mobile');assert.equal(a[0].id,'maya');assert.ok(a[0].reasons.some(r=>r.includes('Android')));state.work.push(...Array.from({length:30},(_,i)=>({id:'test-'+i,owner:'maya',status:'Ready'})));assert.notEqual(recommend(state,ticket,'Mobile')[0].id,'maya');assert.deepEqual(recommend(state,ticket,'Mobile'),recommend(state,ticket,'Mobile'));});
test('invalid input leaves state unchanged; reset creates independent fixtures',()=>{const {state,ticket,draft}=fixture(),before=JSON.stringify(state);for(const patch of [{summary:' '},{priority:'Urgent'},{queue:'Unknown'},{owner:'unknown'}])assert.throws(()=>review(state,ticket.id,{...draft,...patch},'approve'));assert.throws(()=>changeStatus(state,'ENG-104','Closed'));assert.equal(JSON.stringify(state),before);state.tickets[0].title='Changed';assert.notEqual(initialState().tickets[0].title,'Changed');assert.equal(engineers.length,5);});
