import {reviews} from './data.js';
import {themes,months,versions,filterReviews,summarize,groups,monthly,prioritize,insights} from './analysis.js';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selected=reviews,search='',page=1;const size=10;
const monthName=m=>new Date(m+'-01T00:00:00Z').toLocaleDateString('en',{month:'short',year:'numeric',timeZone:'UTC'});
const defs=[['month','Month',months.map(m=>[m,monthName(m)])],['platform','Platform',['iOS','Android']],['version','Version',versions],['rating','Star rating',['1','2','3','4','5']],['theme','Theme',themes],['sentiment','Sentiment',['Positive','Neutral','Negative']]];
$('#filters').innerHTML=defs.map(([id,label,values])=>`<label>${label}<select id="filter-${id}" data-filter="${id}"><option value="">All ${label.toLowerCase()}s</option>${values.map(x=>`<option value="${esc(Array.isArray(x)?x[0]:x)}">${esc(Array.isArray(x)?x[1]:x)}</option>`).join('')}</select></label>`).join('');
const table=(headers,rows,caption='')=>`<table>${caption?`<caption>${caption}</caption>`:''}<thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
function barChart(title,desc,data,max,key='total',unit='reviews'){return `<article class="rp-chart"><h3>${title}</h3><p>${desc}</p><ul class="rp-bars">${data.map(r=>`<li><span>${esc(r.label)}</span><span class="rp-track" aria-hidden="true"><i class="rp-fill" style="width:${Math.min(100,(r[key]||0)/max*100)}%"></i></span><strong>${r[key]===null?'—':key==='average'?r[key].toFixed(2):r[key]}</strong></li>`).join('')}</ul><details><summary>View chart data</summary>${table(['Group',unit,'Sample size'],data.map(r=>[esc(r.label),r[key]===null?'No reviews':key==='average'?r[key].toFixed(2):r[key],r.total]))}</details></article>`;}
function trendChart(rows){const points=monthly(rows),coord=(r,i)=>`${55+i*126},${175-(r.average||0)*28}`,valid=points.filter(p=>p.total);let lines='';for(let i=1;i<points.length;i++)if(points[i-1].total&&points[i].total)lines+=`<line x1="${55+(i-1)*126}" y1="${175-points[i-1].average*28}" x2="${55+i*126}" y2="${175-points[i].average*28}" stroke="#6175b4" stroke-width="3"/>`;return `<article class="rp-chart"><h3>Rating trend over time</h3><p>Mean stars by month, shown on a fixed 1–5 scale. Missing months are not treated as zero.</p><svg class="rp-trend" viewBox="0 0 500 215" role="img" aria-label="Monthly rating trend; exact values and sample sizes in the chart data table below">${[1,2,3,4,5].map(n=>`<line x1="35" y1="${175-n*28}" x2="475" y2="${175-n*28}" stroke="#e1e7f1"/><text x="12" y="${179-n*28}" font-size="11" fill="#526079">${n}</text>`).join('')}${lines}${points.map((r,i)=>`${r.total?`<circle cx="${55+i*126}" cy="${175-r.average*28}" r="5" fill="#304ea5"/><text x="${55+i*126}" y="${160-r.average*28}" text-anchor="middle" font-size="12" fill="#17243c">${r.average.toFixed(2)}</text>`:''}<text x="${55+i*126}" y="185" text-anchor="middle" font-size="12" fill="#526079">${monthName(r.label).slice(0,3)}</text>`).join('')}</svg><details><summary>View chart data</summary>${table(['Month','Average stars','Reviews'],points.map(r=>[monthName(r.label),r.average===null?'No reviews':r.average.toFixed(2),r.total]))}</details></article>`;}
function render(){const f=Object.fromEntries([...document.querySelectorAll('[data-filter]')].map(s=>[s.dataset.filter,s.value]));selected=filterReviews(reviews,f);const m=summarize(selected);$('#selection').textContent=`${m.total} of 180 fictional reviews selected${m.total<10?' · Small sample: interpret with care.':'.'}`;$('#metrics').innerHTML=[['Average rating',m.average===null?'—':m.average.toFixed(2),'out of 5 stars'],['Total reviews',m.total,'in the current selection'],['Negative reviews',m.negative,m.total?(m.negative/m.total*100).toFixed(1)+'% of selected reviews':'No reviews selected'],['Feature requests',m.features,'review type, independent of stars']].map(([label,value,note])=>`<div class="rp-metric"><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`).join('');
const cards=insights(selected);$('#insight-cards').innerHTML=cards.length?cards.map(x=>`<article class="rp-insight"><span class="rp-label">${esc(x.theme)}</span><h3>${x.title}</h3><p><strong>WHAT THE SAMPLE SHOWS</strong>${x.evidence}</p><p><strong>WHY IT MATTERS</strong>${x.why}</p><p class="rp-next"><strong>WHAT I WOULD DO</strong>${x.next}</p></article>`).join(''):`<p class="rp-empty">${m.total?'No featured insight card for this theme. Use the evidence and reviews below to inspect the selected feedback.':'No reviews match these filters. Reset or broaden the selection.'}</p>`;
const rating=groups(selected,'star_rating',[1,2,3,4,5]),theme=groups(selected,'primary_theme',themes).sort((a,b)=>b.total-a.total),negative=groups(selected.filter(r=>r.sentiment==='Negative'),'primary_theme',themes).sort((a,b)=>b.total-a.total);
$('#charts').innerHTML=barChart('Rating distribution','Number of selected reviews at each star rating.',rating,Math.max(1,...rating.map(r=>r.total)))+trendChart(selected)+barChart('Reviews by theme','Each review has one assigned primary theme; totals do not double count.',theme,Math.max(1,...theme.map(r=>r.total)))+barChart('Negative themes','Counts of reviews labeled Negative, grouped by primary theme.',negative,Math.max(1,...negative.map(r=>r.total)))+barChart('Version comparison','Mean stars per fictional version on a fixed 0–5 bar scale. Counts show the size of each sample.',groups(selected,'app_version',versions),5,'average','Average stars');page=1;renderReviews();}
function renderReviews(){const rows=filterReviews(selected,{search}),pages=Math.max(1,Math.ceil(rows.length/size));page=Math.min(page,pages);const start=(page-1)*size;$('#review-count').textContent=`${rows.length} reviews match the explorer search within the current filters. Search affects this table only.`;$('#review-table').innerHTML=rows.length?table(['Date / ID','Platform / version','Rating','Review','Theme / type','Sentiment'],rows.slice(start,start+size).map(r=>[`${r.date}<small>${r.review_id}</small>`,`${r.platform}<small>v${r.app_version}</small>`,`${r.star_rating} / 5`,`<p>${esc(r.review_text)}</p>`,`${esc(r.primary_theme)}<small>${r.review_type}</small>`,r.sentiment]),'Fictional reviews; theme and sentiment labels were assigned for this exercise.'):'<p class="rp-empty">No reviews match. Change the search or the filters above.</p>';$('#page-number').textContent=`Page ${page} of ${pages}`;$('#previous').disabled=page===1;$('#next').disabled=page===pages;}
const priorities=prioritize(reviews);$('#opportunities').innerHTML=['Payments','Login / Authentication','Notifications','Search'].map(theme=>{const p=priorities.find(x=>x.theme===theme);return `<article class="rp-opportunity"><h3>${p.name}</h3><p>${p.frequency} non-positive reviews in this theme.</p><small>Impact: ${p.impact}/5 · Confidence: low</small><p><strong>${p.action}</strong></p><p>${p.note}</p></article>`;}).join('');
$('#priority-table').innerHTML=table(['Opportunity','Feedback frequency','Impact','Business relevance','Confidence','Effort','Score','Recommended action'],priorities.map(p=>[p.name,`${p.frequency} / 180<small>${(p.share*100).toFixed(1)}%</small>`,p.impact,p.relevance,p.confidence,p.effort,p.score.toFixed(1),p.action]),'Full synthetic dataset. Factor values are planning assumptions; the spreadsheet lets you change them.');
$('#checkout-signal').textContent=insights(reviews)[0].evidence.replace('in this selection','in the full synthetic sample')+' I would check this signal against independent sources before attributing it to a release.';
const artifacts=[['Product Insight Report','Themes, trends and questions worth investigating.','Product_Insight_Report.pdf','View PDF'],['Prioritization Matrix','Seven opportunities with editable factors and calculated scores.','Prioritization_Matrix.xlsx','View Spreadsheet'],['Product Requirements Brief','A conditional starting point for checkout reliability.','Product_Requirements_Brief.pdf','View PDF'],['Feedback Analysis Framework','How I move from review context to a product decision.','Feedback_Analysis_Framework.pdf','View PDF']];
$('#artifact-cards').innerHTML=artifacts.map(([name,desc,file,label])=>`<article class="rp-artifact"><span class="rp-label">${file.endsWith('xlsx')?'XLSX':'PDF'}</span><h3>${name}</h3><p>${desc}</p><a href="../../assets/documents/reviewpulse/ReviewPulse_${file}"${file.endsWith('xlsx')?' download':''} aria-label="${label}: ${name}">${label} ↗</a></article>`).join('');
document.querySelectorAll('[data-filter]').forEach(s=>s.addEventListener('change',render));$('#reset').addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(s=>s.value='');$('#search').value='';search='';render();});$('#search').addEventListener('input',e=>{search=e.target.value;page=1;renderReviews();});$('#previous').addEventListener('click',()=>{page--;renderReviews();});$('#next').addEventListener('click',()=>{page++;renderReviews();});render();
