// Independently authored fictional review fixtures. Labels are assigned, not inferred by a model.
export const reviews = [
  {
    "review_id": "RP-009",
    "date": "2026-06-01",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 3,
    "review_text": "Could you show which payment methods are accepted before I reach checkout?",
    "sentiment": "Neutral",
    "primary_theme": "Payments",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-013",
    "date": "2026-06-01",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 3,
    "review_text": "Paying worked, but I had to look around to find the receipt.",
    "sentiment": "Neutral",
    "primary_theme": "Payments",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-017",
    "date": "2026-06-01",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 4,
    "review_text": "Changing my payment method was easy this time.",
    "sentiment": "Positive",
    "primary_theme": "Payments",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-162",
    "date": "2026-06-01",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 2,
    "review_text": "Coming back after a few minutes shows a blank screen.",
    "sentiment": "Negative",
    "primary_theme": "Reliability",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-166",
    "date": "2026-06-01",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 2,
    "review_text": "The screen stays frozen after an error message.",
    "sentiment": "Negative",
    "primary_theme": "Reliability",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-170",
    "date": "2026-06-01",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 4,
    "review_text": "Could you warn me before leaving a form with unsaved changes?",
    "sentiment": "Neutral",
    "primary_theme": "Reliability",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-174",
    "date": "2026-06-01",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 3,
    "review_text": "A clearer offline message would help me know when to try again.",
    "sentiment": "Neutral",
    "primary_theme": "Reliability",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-178",
    "date": "2026-06-01",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 5,
    "review_text": "Good recovery message when the connection was unavailable.",
    "sentiment": "Positive",
    "primary_theme": "Reliability",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-141",
    "date": "2026-06-05",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 1,
    "review_text": "The results don't seem to respect the date I selected.",
    "sentiment": "Negative",
    "primary_theme": "Search",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-145",
    "date": "2026-06-05",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 1,
    "review_text": "The same result appears several times.",
    "sentiment": "Negative",
    "primary_theme": "Search",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-149",
    "date": "2026-06-05",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 3,
    "review_text": "Could search offer related terms when nothing matches?",
    "sentiment": "Neutral",
    "primary_theme": "Search",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-153",
    "date": "2026-06-05",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 4,
    "review_text": "I found what I wanted with just a couple of filters.",
    "sentiment": "Positive",
    "primary_theme": "Search",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-157",
    "date": "2026-06-05",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 4,
    "review_text": "Sorting by availability helped me choose quickly.",
    "sentiment": "Positive",
    "primary_theme": "Search",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-122",
    "date": "2026-06-09",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 2,
    "review_text": "The text overlaps when I increase the phone's font size.",
    "sentiment": "Negative",
    "primary_theme": "User Experience",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-126",
    "date": "2026-06-09",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 2,
    "review_text": "I can't tell which step I am on in the long form.",
    "sentiment": "Negative",
    "primary_theme": "User Experience",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-130",
    "date": "2026-06-09",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 3,
    "review_text": "Could the app remember where I left off in a form?",
    "sentiment": "Neutral",
    "primary_theme": "User Experience",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-134",
    "date": "2026-06-09",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 5,
    "review_text": "Buttons are large enough to use comfortably.",
    "sentiment": "Positive",
    "primary_theme": "User Experience",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-138",
    "date": "2026-06-09",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 5,
    "review_text": "It's easy to see what I need to do next.",
    "sentiment": "Positive",
    "primary_theme": "User Experience",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-095",
    "date": "2026-06-13",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 1,
    "review_text": "The reminder arrived after the booked time had already passed.",
    "sentiment": "Negative",
    "primary_theme": "Notifications",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-099",
    "date": "2026-06-13",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 1,
    "review_text": "Notifications stopped after I changed the settings.",
    "sentiment": "Negative",
    "primary_theme": "Notifications",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-103",
    "date": "2026-06-13",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 3,
    "review_text": "Let me choose reminders separately from promotional updates.",
    "sentiment": "Neutral",
    "primary_theme": "Notifications",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-107",
    "date": "2026-06-13",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 3,
    "review_text": "The alerts are helpful, but the settings names don't explain what each switch does.",
    "sentiment": "Neutral",
    "primary_theme": "Notifications",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-111",
    "date": "2026-06-13",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 4,
    "review_text": "I like that changes are clearly explained in the notification.",
    "sentiment": "Positive",
    "primary_theme": "Notifications",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-115",
    "date": "2026-06-13",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 3,
    "review_text": "Can I mute one booking without switching off every reminder?",
    "sentiment": "Neutral",
    "primary_theme": "Notifications",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-076",
    "date": "2026-06-17",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 2,
    "review_text": "I reach the end of booking and the slot is suddenly unavailable.",
    "sentiment": "Negative",
    "primary_theme": "Booking",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-080",
    "date": "2026-06-17",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 2,
    "review_text": "I can't find the booking I just made in the upcoming list.",
    "sentiment": "Negative",
    "primary_theme": "Booking",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-084",
    "date": "2026-06-17",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 4,
    "review_text": "Please make rescheduling easier to find.",
    "sentiment": "Neutral",
    "primary_theme": "Booking",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-088",
    "date": "2026-06-17",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 3,
    "review_text": "The date picker is usable once you learn how it moves between months.",
    "sentiment": "Neutral",
    "primary_theme": "Booking",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-092",
    "date": "2026-06-17",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 5,
    "review_text": "The confirmation has the details I need in one place.",
    "sentiment": "Positive",
    "primary_theme": "Booking",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-055",
    "date": "2026-06-21",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 1,
    "review_text": "The app slows down after I open several booking details.",
    "sentiment": "Negative",
    "primary_theme": "Performance",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-059",
    "date": "2026-06-21",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 1,
    "review_text": "The app uses a lot of battery during a short session.",
    "sentiment": "Negative",
    "primary_theme": "Performance",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-063",
    "date": "2026-06-21",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 3,
    "review_text": "I'd like a way to stop images loading automatically on mobile data.",
    "sentiment": "Neutral",
    "primary_theme": "Performance",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-067",
    "date": "2026-06-21",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 4,
    "review_text": "Pages open quickly enough that I barely notice loading.",
    "sentiment": "Positive",
    "primary_theme": "Performance",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-071",
    "date": "2026-06-21",
    "platform": "iOS",
    "app_version": "5.0",
    "star_rating": 4,
    "review_text": "Images appeared quickly today, even away from Wi-Fi.",
    "sentiment": "Positive",
    "primary_theme": "Performance",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-032",
    "date": "2026-06-25",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 2,
    "review_text": "After signing in, I see the same sign-in form. Nothing explains why.",
    "sentiment": "Negative",
    "primary_theme": "Login / Authentication",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-036",
    "date": "2026-06-25",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 2,
    "review_text": "The session ended halfway through a form and my changes disappeared.",
    "sentiment": "Negative",
    "primary_theme": "Login / Authentication",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-040",
    "date": "2026-06-25",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 3,
    "review_text": "Could account recovery explain the next step before sending a code?",
    "sentiment": "Neutral",
    "primary_theme": "Login / Authentication",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-044",
    "date": "2026-06-25",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 5,
    "review_text": "The code filled in correctly and I was signed in within moments.",
    "sentiment": "Positive",
    "primary_theme": "Login / Authentication",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-048",
    "date": "2026-06-25",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 5,
    "review_text": "The recovery instructions are easy to follow.",
    "sentiment": "Positive",
    "primary_theme": "Login / Authentication",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-052",
    "date": "2026-06-25",
    "platform": "Android",
    "app_version": "5.0",
    "star_rating": 2,
    "review_text": "Signing out works, but signing back in loops between two screens.",
    "sentiment": "Negative",
    "primary_theme": "Login / Authentication",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-029",
    "date": "2026-07-04",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 1,
    "review_text": "Resetting my password sends me back to the login screen again.",
    "sentiment": "Negative",
    "primary_theme": "Login / Authentication",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-033",
    "date": "2026-07-04",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 1,
    "review_text": "The reset link opens the app but doesn't take me to a password screen.",
    "sentiment": "Negative",
    "primary_theme": "Login / Authentication",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-037",
    "date": "2026-07-04",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 3,
    "review_text": "Please let me see which device sessions are active.",
    "sentiment": "Neutral",
    "primary_theme": "Login / Authentication",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-041",
    "date": "2026-07-04",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 3,
    "review_text": "Login works, though the code instructions are easy to miss.",
    "sentiment": "Neutral",
    "primary_theme": "Login / Authentication",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-045",
    "date": "2026-07-04",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 4,
    "review_text": "I like the clear message when my session expires.",
    "sentiment": "Positive",
    "primary_theme": "Login / Authentication",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-049",
    "date": "2026-07-04",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 1,
    "review_text": "A valid code is rejected once, then works after requesting another.",
    "sentiment": "Negative",
    "primary_theme": "Login / Authentication",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-010",
    "date": "2026-07-08",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 4,
    "review_text": "A clearer receipt download would be useful after booking.",
    "sentiment": "Neutral",
    "primary_theme": "Payments",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-014",
    "date": "2026-07-08",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 3,
    "review_text": "The payment screen has two similar buttons. I paused because I wasn't sure which one would charge me.",
    "sentiment": "Neutral",
    "primary_theme": "Payments",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-018",
    "date": "2026-07-08",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 5,
    "review_text": "I appreciated being able to check the total before the final step.",
    "sentiment": "Positive",
    "primary_theme": "Payments",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-163",
    "date": "2026-07-08",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 1,
    "review_text": "An offline message remains after my connection returns.",
    "sentiment": "Negative",
    "primary_theme": "Reliability",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-167",
    "date": "2026-07-08",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 1,
    "review_text": "I have to restart before the booking list updates.",
    "sentiment": "Negative",
    "primary_theme": "Reliability",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-171",
    "date": "2026-07-08",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 3,
    "review_text": "I'd like an easy way to report an app problem from the error screen.",
    "sentiment": "Neutral",
    "primary_theme": "Reliability",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-175",
    "date": "2026-07-08",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 4,
    "review_text": "The app reopened exactly where I left it.",
    "sentiment": "Positive",
    "primary_theme": "Reliability",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-179",
    "date": "2026-07-08",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 4,
    "review_text": "The list refreshed correctly after I came back to the app.",
    "sentiment": "Positive",
    "primary_theme": "Reliability",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-142",
    "date": "2026-07-12",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 2,
    "review_text": "Clearing a filter still leaves the old results on screen.",
    "sentiment": "Negative",
    "primary_theme": "Search",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-146",
    "date": "2026-07-12",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 2,
    "review_text": "A saved search opens with a different location filter.",
    "sentiment": "Negative",
    "primary_theme": "Search",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-150",
    "date": "2026-07-12",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 3,
    "review_text": "A recently viewed list would make comparing options easier.",
    "sentiment": "Neutral",
    "primary_theme": "Search",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-154",
    "date": "2026-07-12",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 5,
    "review_text": "The results show the details I need before opening them.",
    "sentiment": "Positive",
    "primary_theme": "Search",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-158",
    "date": "2026-07-12",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 5,
    "review_text": "The result count is useful when narrowing a search.",
    "sentiment": "Positive",
    "primary_theme": "Search",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-007",
    "date": "2026-07-15",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 1,
    "review_text": "I lost the basket when payment timed out. Entering everything again is frustrating.",
    "sentiment": "Negative",
    "primary_theme": "Payments",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-119",
    "date": "2026-07-16",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 1,
    "review_text": "The continue button is hidden behind the keyboard.",
    "sentiment": "Negative",
    "primary_theme": "User Experience",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-123",
    "date": "2026-07-16",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 1,
    "review_text": "An important warning disappears before I can finish reading it.",
    "sentiment": "Negative",
    "primary_theme": "User Experience",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-127",
    "date": "2026-07-16",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 3,
    "review_text": "A text-size preference inside the app would help.",
    "sentiment": "Neutral",
    "primary_theme": "User Experience",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-131",
    "date": "2026-07-16",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 3,
    "review_text": "The layout looks clean, but the labels could be more direct.",
    "sentiment": "Neutral",
    "primary_theme": "User Experience",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-135",
    "date": "2026-07-16",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 4,
    "review_text": "The simpler wording makes the booking steps clearer.",
    "sentiment": "Positive",
    "primary_theme": "User Experience",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-096",
    "date": "2026-07-20",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 2,
    "review_text": "I get the same notification twice for one booking.",
    "sentiment": "Negative",
    "primary_theme": "Notifications",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-100",
    "date": "2026-07-20",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 2,
    "review_text": "The badge stays on even after I read all the updates.",
    "sentiment": "Negative",
    "primary_theme": "Notifications",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-104",
    "date": "2026-07-20",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 4,
    "review_text": "Quiet hours would be useful. I don't need routine alerts late at night.",
    "sentiment": "Neutral",
    "primary_theme": "Notifications",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-108",
    "date": "2026-07-20",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 3,
    "review_text": "I found the reminder settings eventually. They were further down than expected.",
    "sentiment": "Neutral",
    "primary_theme": "Notifications",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-112",
    "date": "2026-07-20",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 5,
    "review_text": "Useful reminders without too many interruptions.",
    "sentiment": "Positive",
    "primary_theme": "Notifications",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-116",
    "date": "2026-07-20",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 4,
    "review_text": "I'd prefer different controls for email and phone alerts.",
    "sentiment": "Neutral",
    "primary_theme": "Notifications",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-077",
    "date": "2026-07-24",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 1,
    "review_text": "My saved booking shows a different time from the confirmation page.",
    "sentiment": "Negative",
    "primary_theme": "Booking",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-081",
    "date": "2026-07-24",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 1,
    "review_text": "Changing one detail cleared the rest of the booking form.",
    "sentiment": "Negative",
    "primary_theme": "Booking",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-085",
    "date": "2026-07-24",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 3,
    "review_text": "A reminder of the cancellation window would be helpful.",
    "sentiment": "Neutral",
    "primary_theme": "Booking",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-089",
    "date": "2026-07-24",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 4,
    "review_text": "Found a time and booked it without any trouble.",
    "sentiment": "Positive",
    "primary_theme": "Booking",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-093",
    "date": "2026-07-24",
    "platform": "Android",
    "app_version": "5.1",
    "star_rating": 4,
    "review_text": "I like being able to check availability before filling in the form.",
    "sentiment": "Positive",
    "primary_theme": "Booking",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-056",
    "date": "2026-07-28",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 2,
    "review_text": "Switching tabs leaves a spinner that doesn't finish.",
    "sentiment": "Negative",
    "primary_theme": "Performance",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-060",
    "date": "2026-07-28",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 2,
    "review_text": "Images load late and push the buttons down while I'm tapping.",
    "sentiment": "Negative",
    "primary_theme": "Performance",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-064",
    "date": "2026-07-28",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 3,
    "review_text": "Please show progress for longer loading steps.",
    "sentiment": "Neutral",
    "primary_theme": "Performance",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-068",
    "date": "2026-07-28",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 5,
    "review_text": "Scrolling feels smooth on my older phone.",
    "sentiment": "Positive",
    "primary_theme": "Performance",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-072",
    "date": "2026-07-28",
    "platform": "iOS",
    "app_version": "5.1",
    "star_rating": 5,
    "review_text": "I finished a booking without waiting around for screens.",
    "sentiment": "Positive",
    "primary_theme": "Performance",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-001",
    "date": "2026-08-01",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 1,
    "review_text": "Checkout keeps spinning, then asks me to try again. I cannot tell whether the order went through.",
    "sentiment": "Negative",
    "primary_theme": "Payments",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-005",
    "date": "2026-08-01",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 1,
    "review_text": "The total changes correctly, but checkout ends with a generic error.",
    "sentiment": "Negative",
    "primary_theme": "Payments",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-021",
    "date": "2026-08-01",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 1,
    "review_text": "Checkout returned me to the basket without explaining what happened.",
    "sentiment": "Negative",
    "primary_theme": "Payments",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-025",
    "date": "2026-08-01",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 1,
    "review_text": "There's a blank confirmation area after I tap pay.",
    "sentiment": "Negative",
    "primary_theme": "Payments",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-078",
    "date": "2026-08-03",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 2,
    "review_text": "Rescheduling takes me back to the original date without saving.",
    "sentiment": "Negative",
    "primary_theme": "Booking",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-082",
    "date": "2026-08-03",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 2,
    "review_text": "The calendar allows me to choose a date with no available slots.",
    "sentiment": "Negative",
    "primary_theme": "Booking",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-086",
    "date": "2026-08-03",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 3,
    "review_text": "Could I save a booking draft and finish it later?",
    "sentiment": "Neutral",
    "primary_theme": "Booking",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-090",
    "date": "2026-08-03",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 5,
    "review_text": "The upcoming bookings list is clear and useful.",
    "sentiment": "Positive",
    "primary_theme": "Booking",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-094",
    "date": "2026-08-03",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 5,
    "review_text": "My booking appeared immediately after confirmation.",
    "sentiment": "Positive",
    "primary_theme": "Booking",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-053",
    "date": "2026-08-07",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 1,
    "review_text": "The home screen takes ages to become usable.",
    "sentiment": "Negative",
    "primary_theme": "Performance",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-057",
    "date": "2026-08-07",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 1,
    "review_text": "Typing in the search box feels a second behind my fingers.",
    "sentiment": "Negative",
    "primary_theme": "Performance",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-061",
    "date": "2026-08-07",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 3,
    "review_text": "A lighter mode for slower connections would be welcome.",
    "sentiment": "Neutral",
    "primary_theme": "Performance",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-065",
    "date": "2026-08-07",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 3,
    "review_text": "Most pages are fine, but I notice a pause when moving between tabs.",
    "sentiment": "Neutral",
    "primary_theme": "Performance",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-069",
    "date": "2026-08-07",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 4,
    "review_text": "The app stayed responsive while I compared several options.",
    "sentiment": "Positive",
    "primary_theme": "Performance",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-073",
    "date": "2026-08-07",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 1,
    "review_text": "Returning from the background makes the app unresponsive for several seconds.",
    "sentiment": "Negative",
    "primary_theme": "Performance",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-002",
    "date": "2026-08-08",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 2,
    "review_text": "My basket is ready but the payment button does nothing.",
    "sentiment": "Negative",
    "primary_theme": "Payments",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-006",
    "date": "2026-08-08",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 2,
    "review_text": "Payment fails on the last step even though the saved method is selected.",
    "sentiment": "Negative",
    "primary_theme": "Payments",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-022",
    "date": "2026-08-08",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 2,
    "review_text": "A retry message appeared after verification, but there was no retry button.",
    "sentiment": "Negative",
    "primary_theme": "Payments",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-026",
    "date": "2026-08-08",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 2,
    "review_text": "Payment status still says processing when I reopen the booking.",
    "sentiment": "Negative",
    "primary_theme": "Payments",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-030",
    "date": "2026-08-11",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 2,
    "review_text": "The sign-in code arrives, but the app says it has already expired.",
    "sentiment": "Negative",
    "primary_theme": "Login / Authentication",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-034",
    "date": "2026-08-11",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 2,
    "review_text": "I cannot paste the verification code into the field.",
    "sentiment": "Negative",
    "primary_theme": "Login / Authentication",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-038",
    "date": "2026-08-11",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 4,
    "review_text": "A clearer reminder of the sign-in method I used would help.",
    "sentiment": "Neutral",
    "primary_theme": "Login / Authentication",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-042",
    "date": "2026-08-11",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 3,
    "review_text": "The reset flow is a bit confusing. I eventually found the right screen.",
    "sentiment": "Neutral",
    "primary_theme": "Login / Authentication",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-046",
    "date": "2026-08-11",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 5,
    "review_text": "Password reset worked without having to start over.",
    "sentiment": "Positive",
    "primary_theme": "Login / Authentication",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-050",
    "date": "2026-08-11",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 2,
    "review_text": "I return to the home screen signed out after completing verification.",
    "sentiment": "Negative",
    "primary_theme": "Login / Authentication",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-003",
    "date": "2026-08-15",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 1,
    "review_text": "After the update, returning from payment verification takes me to an empty page.",
    "sentiment": "Negative",
    "primary_theme": "Payments",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-011",
    "date": "2026-08-15",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 3,
    "review_text": "Please add a way to choose a default payment method.",
    "sentiment": "Neutral",
    "primary_theme": "Payments",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-015",
    "date": "2026-08-15",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 4,
    "review_text": "Paid and got confirmation straight away. That's all I needed.",
    "sentiment": "Positive",
    "primary_theme": "Payments",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-019",
    "date": "2026-08-15",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 4,
    "review_text": "Checkout was quick on a slow connection today.",
    "sentiment": "Positive",
    "primary_theme": "Payments",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-023",
    "date": "2026-08-15",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 1,
    "review_text": "The payment screen froze when I switched back from another app.",
    "sentiment": "Negative",
    "primary_theme": "Payments",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-027",
    "date": "2026-08-15",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 1,
    "review_text": "The error disappears too quickly to read, leaving me unsure whether to pay again.",
    "sentiment": "Negative",
    "primary_theme": "Payments",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-164",
    "date": "2026-08-15",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 2,
    "review_text": "The app forgot a change that it had said was saved.",
    "sentiment": "Negative",
    "primary_theme": "Reliability",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-168",
    "date": "2026-08-15",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 2,
    "review_text": "Rotating the phone clears the form unexpectedly.",
    "sentiment": "Negative",
    "primary_theme": "Reliability",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-172",
    "date": "2026-08-15",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 3,
    "review_text": "Please show when booking details were last refreshed.",
    "sentiment": "Neutral",
    "primary_theme": "Reliability",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-176",
    "date": "2026-08-15",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 5,
    "review_text": "My changes were still there after a connection interruption.",
    "sentiment": "Positive",
    "primary_theme": "Reliability",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-180",
    "date": "2026-08-15",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 5,
    "review_text": "The app stayed stable while I moved between several screens.",
    "sentiment": "Positive",
    "primary_theme": "Reliability",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-139",
    "date": "2026-08-19",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 1,
    "review_text": "Searching for a name gives no result even when I can browse to it.",
    "sentiment": "Negative",
    "primary_theme": "Search",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-143",
    "date": "2026-08-19",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 1,
    "review_text": "Typing a small spelling mistake gives an empty list.",
    "sentiment": "Negative",
    "primary_theme": "Search",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-147",
    "date": "2026-08-19",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 3,
    "review_text": "I'd like to save a set of search filters.",
    "sentiment": "Neutral",
    "primary_theme": "Search",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-151",
    "date": "2026-08-19",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 3,
    "review_text": "The filters work, but I can't easily see which ones are active.",
    "sentiment": "Neutral",
    "primary_theme": "Search",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-155",
    "date": "2026-08-19",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 4,
    "review_text": "Search handled the exact phrase I entered well.",
    "sentiment": "Positive",
    "primary_theme": "Search",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-159",
    "date": "2026-08-19",
    "platform": "Android",
    "app_version": "5.2",
    "star_rating": 3,
    "review_text": "There are many filter choices; a short description would help me choose.",
    "sentiment": "Neutral",
    "primary_theme": "Search",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-004",
    "date": "2026-08-22",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 2,
    "review_text": "Tried paying twice. Both attempts stopped before the confirmation screen.",
    "sentiment": "Negative",
    "primary_theme": "Payments",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-024",
    "date": "2026-08-22",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 2,
    "review_text": "I can browse normally. Only the final payment step gets stuck.",
    "sentiment": "Negative",
    "primary_theme": "Payments",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-028",
    "date": "2026-08-22",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 2,
    "review_text": "The checkout page reloads instead of showing the result.",
    "sentiment": "Negative",
    "primary_theme": "Payments",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-120",
    "date": "2026-08-23",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 2,
    "review_text": "Some labels are too faint for me to read comfortably.",
    "sentiment": "Negative",
    "primary_theme": "User Experience",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-124",
    "date": "2026-08-23",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 2,
    "review_text": "The close icon is difficult to tap accurately.",
    "sentiment": "Negative",
    "primary_theme": "User Experience",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-128",
    "date": "2026-08-23",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 4,
    "review_text": "Please let me save my most-used choices.",
    "sentiment": "Neutral",
    "primary_theme": "User Experience",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-132",
    "date": "2026-08-23",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 3,
    "review_text": "I needed a moment to understand the new navigation order.",
    "sentiment": "Neutral",
    "primary_theme": "User Experience",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-136",
    "date": "2026-08-23",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 5,
    "review_text": "I like having a visible back option on each screen.",
    "sentiment": "Positive",
    "primary_theme": "User Experience",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-097",
    "date": "2026-08-27",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 1,
    "review_text": "Tapping a reminder opens the home page instead of the booking.",
    "sentiment": "Negative",
    "primary_theme": "Notifications",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-101",
    "date": "2026-08-27",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 1,
    "review_text": "A booking change appeared in the app but no alert arrived.",
    "sentiment": "Negative",
    "primary_theme": "Notifications",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-105",
    "date": "2026-08-27",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 3,
    "review_text": "I'd like to choose how far ahead a booking reminder arrives.",
    "sentiment": "Neutral",
    "primary_theme": "Notifications",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-109",
    "date": "2026-08-27",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 4,
    "review_text": "The reminder gave me enough time to prepare.",
    "sentiment": "Positive",
    "primary_theme": "Notifications",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-113",
    "date": "2026-08-27",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 4,
    "review_text": "The app respected my notification choice.",
    "sentiment": "Positive",
    "primary_theme": "Notifications",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-117",
    "date": "2026-08-27",
    "platform": "iOS",
    "app_version": "5.2",
    "star_rating": 3,
    "review_text": "A weekend quiet schedule would fit my routine better.",
    "sentiment": "Neutral",
    "primary_theme": "Notifications",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-062",
    "date": "2026-09-01",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 4,
    "review_text": "Could recently opened bookings be available without reloading everything?",
    "sentiment": "Neutral",
    "primary_theme": "Performance",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-087",
    "date": "2026-09-02",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 3,
    "review_text": "Booking works, but there are more confirmation screens than I expected.",
    "sentiment": "Neutral",
    "primary_theme": "Booking",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-110",
    "date": "2026-09-03",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 5,
    "review_text": "Opening an alert took me straight to the right booking.",
    "sentiment": "Positive",
    "primary_theme": "Notifications",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-140",
    "date": "2026-09-03",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 2,
    "review_text": "My filters reset whenever I open a result.",
    "sentiment": "Negative",
    "primary_theme": "Search",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-008",
    "date": "2026-09-04",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 2,
    "review_text": "The app says payment pending and gives no advice about what to do next.",
    "sentiment": "Negative",
    "primary_theme": "Payments",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-137",
    "date": "2026-09-04",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 4,
    "review_text": "The form explains mistakes without wiping my entries.",
    "sentiment": "Positive",
    "primary_theme": "User Experience",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-165",
    "date": "2026-09-04",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 1,
    "review_text": "Opening an old booking crashes the app.",
    "sentiment": "Negative",
    "primary_theme": "Reliability",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-039",
    "date": "2026-09-05",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 3,
    "review_text": "I'd like an option to stay signed in on my own device.",
    "sentiment": "Neutral",
    "primary_theme": "Login / Authentication",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-160",
    "date": "2026-09-05",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 3,
    "review_text": "The empty-results message could suggest what to change.",
    "sentiment": "Neutral",
    "primary_theme": "Search",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-066",
    "date": "2026-09-06",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 3,
    "review_text": "The first launch feels slow. Later visits are better.",
    "sentiment": "Neutral",
    "primary_theme": "Performance",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-091",
    "date": "2026-09-07",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 4,
    "review_text": "Changing my date was easier than calling someone.",
    "sentiment": "Positive",
    "primary_theme": "Booking",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-121",
    "date": "2026-09-07",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 1,
    "review_text": "Back takes me all the way home instead of one step.",
    "sentiment": "Negative",
    "primary_theme": "User Experience",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-114",
    "date": "2026-09-08",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 5,
    "review_text": "Updates arrived at a sensible time today.",
    "sentiment": "Positive",
    "primary_theme": "Notifications",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-144",
    "date": "2026-09-08",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 2,
    "review_text": "The search result count changes but the list doesn't update.",
    "sentiment": "Negative",
    "primary_theme": "Search",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-012",
    "date": "2026-09-09",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 3,
    "review_text": "I would like to see a breakdown of the total before confirming.",
    "sentiment": "Neutral",
    "primary_theme": "Payments",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-169",
    "date": "2026-09-09",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 3,
    "review_text": "An offline view of booking details would be reassuring.",
    "sentiment": "Neutral",
    "primary_theme": "Reliability",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-043",
    "date": "2026-09-10",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 4,
    "review_text": "Getting back into my account was straightforward.",
    "sentiment": "Positive",
    "primary_theme": "Login / Authentication",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-075",
    "date": "2026-09-10",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 1,
    "review_text": "A selected time disappears when I return from the details screen.",
    "sentiment": "Negative",
    "primary_theme": "Booking",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-070",
    "date": "2026-09-11",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 5,
    "review_text": "It recovered nicely when my connection dropped for a moment.",
    "sentiment": "Positive",
    "primary_theme": "Performance",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-098",
    "date": "2026-09-11",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 2,
    "review_text": "A canceled booking still sends reminders.",
    "sentiment": "Negative",
    "primary_theme": "Notifications",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-125",
    "date": "2026-09-12",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 1,
    "review_text": "The selected option is only shown by color and I keep missing it.",
    "sentiment": "Negative",
    "primary_theme": "User Experience",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-118",
    "date": "2026-09-13",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 3,
    "review_text": "Please let me preview what a reminder looks like in settings.",
    "sentiment": "Neutral",
    "primary_theme": "Notifications",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-148",
    "date": "2026-09-13",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 4,
    "review_text": "Please add a way to compare two results side by side.",
    "sentiment": "Neutral",
    "primary_theme": "Search",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-016",
    "date": "2026-09-14",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 5,
    "review_text": "The price breakdown is much clearer than I expected.",
    "sentiment": "Positive",
    "primary_theme": "Payments",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-054",
    "date": "2026-09-14",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 2,
    "review_text": "Scrolling through results is choppy even with only a few items.",
    "sentiment": "Negative",
    "primary_theme": "Performance",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-173",
    "date": "2026-09-14",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 3,
    "review_text": "The app recovers after an error, though I am not sure whether my changes saved.",
    "sentiment": "Neutral",
    "primary_theme": "Reliability",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-047",
    "date": "2026-09-15",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 4,
    "review_text": "Sign-in is less of a chore now.",
    "sentiment": "Positive",
    "primary_theme": "Login / Authentication",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-079",
    "date": "2026-09-15",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 1,
    "review_text": "The cancel button reports an error but doesn't say whether anything changed.",
    "sentiment": "Negative",
    "primary_theme": "Booking",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-074",
    "date": "2026-09-16",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 2,
    "review_text": "The details panel takes much longer to open than the results list.",
    "sentiment": "Negative",
    "primary_theme": "Performance",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-102",
    "date": "2026-09-16",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 2,
    "review_text": "The notification text cuts off the part explaining what changed.",
    "sentiment": "Negative",
    "primary_theme": "Notifications",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-129",
    "date": "2026-09-17",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 3,
    "review_text": "I'd like a short explanation beside unfamiliar options.",
    "sentiment": "Neutral",
    "primary_theme": "User Experience",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-031",
    "date": "2026-09-18",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 1,
    "review_text": "I keep getting logged out while checking a booking.",
    "sentiment": "Negative",
    "primary_theme": "Login / Authentication",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-152",
    "date": "2026-09-18",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 3,
    "review_text": "Sorting is useful once I find it beneath the search box.",
    "sentiment": "Neutral",
    "primary_theme": "Search",
    "review_type": "Usability Feedback"
  },
  {
    "review_id": "RP-020",
    "date": "2026-09-19",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 5,
    "review_text": "Receipt and booking details match. No confusion after paying.",
    "sentiment": "Positive",
    "primary_theme": "Payments",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-058",
    "date": "2026-09-19",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 2,
    "review_text": "Loading a saved booking is slower than finding it again from scratch.",
    "sentiment": "Negative",
    "primary_theme": "Performance",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-177",
    "date": "2026-09-19",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 4,
    "review_text": "I haven't had a crash during the bookings I tried.",
    "sentiment": "Positive",
    "primary_theme": "Reliability",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-051",
    "date": "2026-09-20",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 1,
    "review_text": "The recovery page gets stuck before I can enter a new password.",
    "sentiment": "Negative",
    "primary_theme": "Login / Authentication",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-083",
    "date": "2026-09-20",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 3,
    "review_text": "I'd like to compare nearby dates without restarting the search.",
    "sentiment": "Neutral",
    "primary_theme": "Booking",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-106",
    "date": "2026-09-21",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 3,
    "review_text": "Please offer a daily summary instead of a separate alert for every update.",
    "sentiment": "Neutral",
    "primary_theme": "Notifications",
    "review_type": "Feature Request"
  },
  {
    "review_id": "RP-133",
    "date": "2026-09-22",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 4,
    "review_text": "The screens are uncluttered and easy to follow.",
    "sentiment": "Positive",
    "primary_theme": "User Experience",
    "review_type": "Positive Feedback"
  },
  {
    "review_id": "RP-161",
    "date": "2026-09-22",
    "platform": "iOS",
    "app_version": "5.3",
    "star_rating": 1,
    "review_text": "The app closed while I was reading a booking.",
    "sentiment": "Negative",
    "primary_theme": "Reliability",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-035",
    "date": "2026-09-23",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 1,
    "review_text": "Sign-in fails after I return from the code message.",
    "sentiment": "Negative",
    "primary_theme": "Login / Authentication",
    "review_type": "Issue"
  },
  {
    "review_id": "RP-156",
    "date": "2026-09-23",
    "platform": "Android",
    "app_version": "5.3",
    "star_rating": 5,
    "review_text": "It's easy to clear everything and start again.",
    "sentiment": "Positive",
    "primary_theme": "Search",
    "review_type": "Positive Feedback"
  }
];
